# Data
path: dataset
train: train/images  # train images (relative to 'path')
val: val/images  # val images (relative to 'path')

# Keypoints
kpt_shape: [13, 3]  # [number of keypoints, number of dim]

# Classes
names:
  0: weld
